# Generated by Django 4.2.16 on 2024-10-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('info', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='img')),
            ],
        ),
    ]
